# Generated by Django 5.1.7 on 2025-03-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_state_roomnr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_state',
            new_name='GameState',
        ),
    ]
