# Generated by Django 5.1.7 on 2025-03-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_game_state_gamestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStateTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.JSONField()),
                ('valid_pos', models.JSONField()),
                ('order', models.IntegerField()),
                ('roomnr', models.IntegerField(unique=True)),
                ('state_players', models.JSONField()),
            ],
        ),
    ]
