# Generated by Django 5.1.7 on 2025-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamestatetemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatetemp',
            name='selected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamestatetemp',
            name='valid_pos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
