# Generated by Django 5.1.7 on 2025-03-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gamestatetemp_selected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='order',
            new_name='turnwise',
        ),
        migrations.RenameField(
            model_name='gamestatetemp',
            old_name='order',
            new_name='turnwise',
        ),
    ]
