# Generated by Django 5.1.7 on 2025-03-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_order_gamestate_turnwise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnwise', models.IntegerField()),
                ('roomnr', models.IntegerField(unique=True)),
                ('state_players', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStateBetween',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.JSONField(blank=True, null=True)),
                ('valid_pos', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GameStateTemp',
        ),
    ]
