# Generated by Django 5.1.7 on 2025-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gamestate1_gamestatebetween_delete_gamestatetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStateBetween1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnr', models.IntegerField(unique=True)),
                ('selected', models.JSONField(blank=True, null=True)),
                ('valid_pos', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GameStateBetween',
        ),
    ]
