# Generated by Django 5.1.7 on 2025-03-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gamestatebetween1_delete_gamestatebetween'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate1',
            name='nrmove',
            field=models.IntegerField(default=0),
        ),
    ]
