# Generated by Django 5.1.7 on 2025-03-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_gamestate1_turnwise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnr', models.IntegerField(unique=True)),
                ('a2b', models.JSONField()),
                ('turnwise', models.IntegerField(default=0)),
                ('nrmove', models.IntegerField(default=0)),
            ],
        ),
    ]
