# Generated by Django 5.1.7 on 2025-03-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_moves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate1',
            old_name='nrmove',
            new_name='movenr',
        ),
        migrations.RenameField(
            model_name='moves',
            old_name='nrmove',
            new_name='movenr',
        ),
    ]
