# Generated by Django 5.1.7 on 2025-03-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_gamestate3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnr', models.IntegerField(unique=True)),
                ('movenr', models.IntegerField(default=0)),
                ('coord_from', models.JSONField()),
                ('coord_to', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Moves',
        ),
    ]
