# Generated by Django 5.1.7 on 2025-03-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_moves1_delete_moves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='GameState1',
        ),
        migrations.DeleteModel(
            name='GameState2',
        ),
        migrations.DeleteModel(
            name='GameStateBetween1',
        ),
    ]
