# Generated by Django 5.1.7 on 2025-03-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_delete_board_delete_gamestate1_delete_gamestate2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves1',
            name='roomnr',
            field=models.IntegerField(),
        ),
    ]
