# Generated by Django 5.1.7 on 2025-03-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_moves1_roomnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate3',
            name='selected',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='gamestate3',
            name='valid_pos',
            field=models.JSONField(default=[]),
        ),
    ]
