# Generated by Django 5.1.7 on 2025-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_gamestate3_selected_alter_gamestate3_valid_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate3',
            name='selected',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gamestate3',
            name='valid_pos',
            field=models.JSONField(default=list),
        ),
    ]
