# Generated by Django 5.1.7 on 2025-03-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_gamestate3_selected_alter_gamestate3_valid_pos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='gamestate3',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
