# Generated by Django 5.1.7 on 2025-04-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_delete_score_gamestate3_win'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameState',
            new_name='GameStateEnd',
        ),
        migrations.RenameModel(
            old_name='GameState3',
            new_name='GameStateTemp',
        ),
        migrations.RenameModel(
            old_name='Moves1',
            new_name='Moves',
        ),
    ]
