name: Django CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: back.settings
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: test1
      run: echo "test1 repo var ${{ vars.REPO_VAR2 }}"

    - name: test2
      run: echo "test2 repo sec ${{ secrets.REPO_SEC2 }}"
